### ISSUE TITLE
Cannot parse own tox.ini

### ISSUE THREAD

**Issue by pombredanne** [pyupio/dparse#6]
* Dependency Parser version:
0.1.0 from Pypi
* Python version:
2.7.6
* Operating System:
Ubuntu 14.04 LTS
### Description
When parsing the content of this project tox.ini I get this stack trace. `t` contains the tox.ini text at 
https://github.com/pyupio/dparse/blob/b0e830d98cf51afb5c68f18a158930d2aa8a221d/tox.ini

```
b=parse(t,tox_ini)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/dparse/python2.7/site-packages/dparse/parser.py", line 283, in parse
    return dep_file.parse()
  File "/tmp/dparse/python2.7/site-packages/dparse/dependencies.py", line 178, in parse
    self.parser.parse()
  File "/tmp/dparse/python2.7/site-packages/dparse/parser.py", line 231, in parse
    req = RequirementsTXTLineParser.parse(line)
  File "/tmp/dparse/python2.7/site-packages/dparse/parser.py", line 41, in parse
    parsed, = parse_requirements(line)
  File "/tmp/dparse/python2.7/site-packages/pkg_resources/__init__.py", line 2826, in parse_requirements
    yield Requirement(line)
  File "/tmp/dparse/python2.7/site-packages/pkg_resources/__init__.py", line 2836, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'-r{toxin'"
```

**Comment by pombredanne** [comment]
Thanks!
